# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules
# This file will not be modified during dotfiles updates

# airctl WiFi manager
windowrule = match:class ^(airctl)$, float on, center on, size 400 600

# SwayNotificationCenter rules
layerrule = blur, swaync-control-center
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-notification-window
